package com.fjr619.kmmweather.domain.model

data class Hour(
    val timeEpoch: Long,
    val time: String,
    val temperatureInCelsius: Double,
    val temperatureInFahrenheit: Double,
    val isDay: Int,
    val condition: Condition,
    val windSpeedMph: Double,
    val windSpeedKph: Double,
    val windDirectionDegrees: Int,
    val windDirection: String,
    val pressureMb: Double,
    val pressureInches: Double,
    val precipitationMm: Double,
    val precipitationInches: Double,
    val humidity: Int,
    val cloudCoverage: Int,
    val feelsLikeTemperatureInCelsius: Double,
    val feelsLikeTemperatureInFahrenheit: Double,
    val windchillTemperatureInCelsius: Double,
    val windchillTemperatureInFahrenheit: Double,
    val heatIndexCelsius: Double,
    val heatIndexFahrenheit: Double,
    val dewPointCelsius: Double,
    val dewPointFahrenheit: Double,
    val willItRain: Int,
    val chanceOfRain: Int,
    val willItSnow: Int,
    val chanceOfSnow: Int,
    val visibilityKm: Double,
    val visibilityMiles: Double,
    val windGustMph: Double,
    val windGustKph: Double,
    val uvIndex: Double,
    val airQuality: AirQuality?,
)